apiVersion: v1
kind: Service
metadata:
  name: guestbook
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  guestbook-mapping-staging
      host: ^staging(\-?k8s.*|.)?guestbook.evanlocke.me$
      host_regex: true
      prefix: /
      service: guestbook.staging:80
