apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./ambassador-rbac.yaml
- ./ingress.yaml
- ./namespaces.yaml
- ./sealedsecrets.yaml

namespace: default

commonLabels:
  app.kubernetes.io/instance: cluster

configurations:
- ./metadatalabelsonly.yaml
