apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml
- ./prod.yaml
- ./staging.yaml
- ./github-deploy-key.json
- ./argocd-secret.json
- ./install.yaml

  # This bootstraps ArgoCD apps that will bootstrap (and sync) all of the
  # ArgoCD apps in /argocd/apps (including the bootstrapper app)
  #- ../apps/apps.yaml

patchesStrategicMerge:
- ./service.yaml

# We're applying the namespace here so that install.yaml
# can be left unchanged from the ArgoCD installation yaml
#
# To upgrade ArgoCD:
# curl https://raw.githubusercontent.com/argoproj/argo-cd/v1.0.1/manifests/install.yaml > install.yaml
namespace: argocd

commonLabels:
  app.kubernetes.io/instance: cluster

configurations:
- ./metadatalabelsonly.yaml
