---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster/env/prod
    repoURL: git@github.com:elocke/gitops-example.git
    targetRevision: HEAD
