---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-guestbook
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: prod
  source:
    environment: prod
    path: apps/guestbook/env/prod
    repoURL: git@github.com:elocke/gitops-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-guestbook
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: staging
  source:
    environment: staging
    path: apps/guestbook/env/staging
    repoURL: git@github.com:elocke/gitops-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
